services:
  h2-database:
    container_name: h2-database
    image: oscarfonts/h2
    ports:
      - "1521:1521"   # cli
      - "81:81"       # web interface
    volumes:
      - ./h2-data:/opt/h2-data
    environment:
      H2_OPTIONS: -ifNotExists
    networks:
      - persistence
    restart: unless-stopped

networks:
  persistence: { }